name: app

type: "php:8.1"

dependencies:
    php:
        wp-cli/wp-cli-bundle: "^2.4"
        psy/psysh: "^0.10.4"

relationships:
    database: "db:mysql"

variables:
    php:
        session.gc_maxlifetime: '200000'
        session.cookie_lifetime: '2000000'
        pcre.backtrack_limit: '200000'
        pcre.recursion_limit: '200000'
        upload_max_filesize: 64M
        post_max_size: 64M
        memory_limit: 256M

web:
    locations:
        "/":
            root: "wordpress"
            passthru: "/index.php"
            index:
                - "index.php"
            expires: 600
            scripts: true
            allow: true
            rules:
                ^/composer\.json:
                    allow: false
                ^/license\.txt$:
                    allow: false
                ^/readme\.html$:
                    allow: false
                \.(css|js|gif|jpe?g|png|ttf|eot|woff2?|otf|html|ico|svg?)$:
                    allow: true
        "/wp-content/cache":
            root: "wordpress/wp-content/cache"
            scripts: false
            allow: false
        "/wp-content/uploads":
            root: "wordpress/wp-content/uploads"
            scripts: false
            allow: false
            rules:
                '(?<!-lock)\.(?i:jpe?g|gif|png|svg|bmp|ico|css|js(?:on)?|eot|ttf|woff|woff2|pdf|docx?|xlsx?|pp[st]x?|psd|odt|key|mp[2-5g]|m4[av]|og[gv]|wav|mov|wm[av]|avi|3g[p2])$':
                    allow: true
                    expires: 1w

disk: 2048

mounts:
    "wordpress/wp-content/cache":
        source: local
        source_path: "cache"
    "wordpress/wp-content/uploads":
        source: local
        source_path: "uploads"

hooks:
    build: |
        set -e
        # Download and extract WordPress
        curl -o wordpress.tar.gz -fL "https://wordpress.org/latest.tar.gz"
        tar -xzf wordpress.tar.gz
        rm wordpress.tar.gz
        
        # Copy custom plugins
        mkdir -p wordpress/wp-content/plugins
        cp -r wp-content/plugins/espbot wordpress/wp-content/plugins/
        
        # Copy custom themes
        mkdir -p wordpress/wp-content/themes
        cp -r wp-content/themes/espbot wordpress/wp-content/themes/
        
        # Copy WordPress configuration
        cp wp-config-render.php wordpress/wp-config.php
    deploy: |
        cd wordpress
        wp cache flush
        wp core update-db
        wp cron event run --due-now
