"https://{default}/":
    type: upstream
    upstream: "app:http"
    cache:
        enabled: true
    ssi:
        enabled: false

"https://www.{default}/":
    type: redirect
    to: "https://{default}/"

"http://45.147.251.181/":
    type: proxy
    to: "https://45.147.251.181/"
    cache:
        enabled: true
        default_ttl: 0
    http:
        insecure: true  # Allow insecure SSL connections
